### ISSUE TITLE
Hardware and Coding

### ISSUE THREAD

**Issue by mainframe2017** [wassgha/MirrorOS#6]
This smart run on Raspberry pi or on traditional PC?. Also provide guide for configure this smart mirror.

**Comment by prosperi** [comment]
MirrorOS will run on both platforms, but the project is under development. Final documentation will be published during next 2 months.

**Comment by wassgha** [comment]
Rough instructions to get you started:
1. Install NodeJS
2. Install MiniConda
3. Run : 
`pip install pillow` then
`conda install -c menpo opencv3 `
6. Go to the folder where you cloned this repository then run
`npm install`
`npm start`

**Comment by cowboysdude** [comment]
I'm getting a javascript error:

Cannot find module 'socket.io-client/dist/socket.io.min.js'

After I follow the above instructions...  What is happening?

**Comment by wassgha** [comment]
Try
`npm install socket.io`

**Comment by cowboysdude** [comment]
Will do.... when I get home later I'll give it a shot :)  Thanks!

**Comment by mainframe2017** [comment]
Hello team

Please help me out from this trouble.

Thank you
Maulik patel
